{
 "title": "My first",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(\n  100 * (1 - sum by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n             / sum by(instance)(rate(node_cpu_seconds_total[5m])))\n)",
     "legendFormat": "CPU utilization"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{\n  fstype!~\"tmpfs|overlay|nsfs|aufs|squashfs|ramfs|cgroup2?\",\n  device!~\"^rootfs$\"\n} / 1024 / 1024 / 1024",
     "legendFormat": "Free space"
    }
   ]
  },
  {
   "title": "CPU Load Average 1/5/15",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPU Load Average 1" },
    { "expr": "node_load5", "legendFormat": "CPU Load Average 5" },
    { "expr": "node_load15", "legendFormat": "CPU Load Average 15" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024",
     "legendFormat": "Free memory"
    }
   ]
  }
 ]
}